export interface Service {
    id: number;
    category: string;
    title: string;
    description: string;
    featured: boolean;
}

export const services: Service[] = [
    {
        id: 1,
        category: "Government Services",
        title: "eCitizen Services",
        description:
            "Professional assistance with eCitizen applications and government services.",
        featured: true,
    },
    {
        id: 2,
        category: "Government Services",
        title: "KRA iTax Services",
        description:
            "KRA iTax registration, filing, compliance and related tax services.",
        featured: true,
    },
    {
        id: 3,
        category: "Government Services",
        title: "NTSA Services",
        description:
            "Driving licence, vehicle registration and NTSA online services.",
        featured: true,
    },
    {
        id: 4,
        category: "Government Services",
        title: "NSSF Services",
        description:
            "Registration, member updates and contribution assistance.",
        featured: false,
    },
    {
        id: 5,
        category: "Government Services",
        title: "SHA Registration & Updates",
        description:
            "Registration and updating of Social Health Authority records.",
        featured: true,
    },
    {
        id: 6,
        category: "Government Services",
        title: "NHIF Historical Records Assistance",
        description:
            "Support with historical NHIF records and migration assistance.",
        featured: false,
    },
    {
        id: 7,
        category: "Government Services",
        title: "HELB Services",
        description:
            "Loan application, compliance and account support.",
        featured: false,
    },
    {
        id: 8,
        category: "Government Services",
        title: "KUCCPS Services",
        description:
            "Course application, revision and placement assistance.",
        featured: false,
    },
    {
        id: 9,
        category: "Government Services",
        title: "Immigration Services",
        description:
            "Online immigration applications and document processing support.",
        featured: true,
    },
    {
        id: 10,
        category: "Government Services",
        title: "Passport Applications",
        description:
            "Professional assistance with Kenyan passport applications.",
        featured: true,
    },
    {
        id: 11,
        category: "Government Services",
        title: "Certificate of Good Conduct",
        description:
            "Application support for Certificates of Good Conduct.",
        featured: true,
    },
    {
        id: 12,
        category: "Government Services",
        title: "Birth Certificate Applications",
        description:
            "Application and follow-up services for birth certificates.",
        featured: false,
    },
    {
        id: 13,
        category: "Government Services",
        title: "Business Registration",
        description:
            "Business name search, registration and compliance support.",
        featured: true,
    },
    {
        id: 14,
        category: "Government Services",
        title: "CR12 Applications",
        description:
            "CR12 application and company records retrieval.",
        featured: false,
    },
    {
        id: 15,
        category: "Government Services",
        title: "Company Registration",
        description:
            "Complete company incorporation and registration services.",
        featured: true,
    },
    {
        id: 16,
        category: "Government Services",
        title: "BRS Services",
        description:
            "Business Registration Service support and applications.",
        featured: false,
    },
    {
        id: 17,
        category: "Government Services",
        title: "Huduma Services",
        description:
            "Assistance with online Huduma services and applications.",
        featured: false,
    },
    {
        id: 18,
        category: "Government Services",
        title: "Kenya Power Services",
        description:
            "Electricity applications, reconnections and customer services.",
        featured: false,
    },
    {
        id: 19,
        category: "Government Services",
        title: "Water Company Applications",
        description:
            "Water connection and account management services.",
        featured: false,
    },
    {
        id: 20,
        category: "Government Services",
        title: "County Government Online Services",
        description:
            "Digital county applications, permits and licensing support.",
        featured: false,
    },
    {
        id: 21,
        category: "Government Services",
        title: "Court e-Filing Assistance",
        description:
            "Support with court e-filing systems and document submission.",
        featured: false,
    },
    {
        id: 22,
        category: "Tax Consultancy",
        title: "KRA PIN Registration",
        description: "Registration of new KRA PINs for individuals and businesses.",
        featured: true,
    },
    {
        id: 23,
        category: "Tax Consultancy",
        title: "PIN Retrieval",
        description: "Retrieve lost or forgotten KRA PIN certificates.",
        featured: false,
    },
    {
        id: 24,
        category: "Tax Consultancy",
        title: "PIN Update",
        description: "Update taxpayer information in the KRA system.",
        featured: false,
    },
    {
        id: 25,
        category: "Tax Consultancy",
        title: "Tax Compliance Certificate (TCC)",
        description: "Application and renewal of Tax Compliance Certificates.",
        featured: true,
    },
    {
        id: 26,
        category: "Tax Consultancy",
        title: "Tax Returns Filing",
        description: "Professional filing of all KRA tax returns.",
        featured: true,
    },
    {
        id: 27,
        category: "Tax Consultancy",
        title: "Nil Returns",
        description: "Submission of annual nil tax returns.",
        featured: false,
    },
    {
        id: 28,
        category: "Tax Consultancy",
        title: "Individual Returns",
        description: "Preparation and filing of individual income tax returns.",
        featured: true,
    },
    {
        id: 29,
        category: "Tax Consultancy",
        title: "Business Returns",
        description: "Preparation and filing of business tax returns.",
        featured: true,
    },
    {
        id: 30,
        category: "Tax Consultancy",
        title: "Rental Income Returns",
        description: "Preparation and filing of rental income tax returns.",
        featured: false,
    },
    {
        id: 31,
        category: "Tax Consultancy",
        title: "PAYE Returns",
        description: "Monthly PAYE return preparation and filing.",
        featured: true,
    },
    {
        id: 32,
        category: "Tax Consultancy",
        title: "VAT Returns",
        description: "VAT registration, preparation and monthly filing.",
        featured: true,
    },
    {
        id: 33,
        category: "Tax Consultancy",
        title: "Turnover Tax (TOT)",
        description: "Registration and filing of Turnover Tax returns.",
        featured: false,
    },
    {
        id: 34,
        category: "Tax Consultancy",
        title: "Excise Tax Assistance",
        description: "Support with excise duty compliance and filing.",
        featured: false,
    },
    {
        id: 35,
        category: "Tax Consultancy",
        title: "Digital Service Tax Guidance",
        description: "Professional guidance on Digital Service Tax obligations.",
        featured: false,
    },
    {
        id: 36,
        category: "Tax Consultancy",
        title: "Capital Gains Tax Guidance",
        description: "Advice and support on Capital Gains Tax compliance.",
        featured: false,
    },
    {
        id: 37,
        category: "Tax Consultancy",
        title: "Tax Objection Assistance",
        description: "Preparation and submission of tax objections.",
        featured: true,
    },
    {
        id: 38,
        category: "Tax Consultancy",
        title: "Tax Advisory",
        description: "Professional tax advisory for individuals and businesses.",
        featured: true,
    },
    {
        id: 39,
        category: "Tax Consultancy",
        title: "Tax Planning",
        description: "Strategic tax planning to improve compliance and efficiency.",
        featured: true,
    },
    {
        id: 40,
        category: "Tax Consultancy",
        title: "Tax Education",
        description: "Training and education on Kenyan tax systems.",
        featured: false,
    },
    {
        id: 41,
        category: "Tax Consultancy",
        title: "KRA System Navigation",
        description: "Guidance on using the KRA iTax platform.",
        featured: false,
    },
    {
        id: 42,
        category: "Tax Consultancy",
        title: "Tax Registration",
        description: "Registration for various tax obligations.",
        featured: false,
    },
    {
        id: 43,
        category: "Tax Consultancy",
        title: "Withholding Tax Assistance",
        description: "Support with withholding tax calculations and compliance.",
        featured: false,
    },
    {
        id: 44,
        category: "Tax Consultancy",
        title: "Tax Record Analysis",
        description: "Review and analysis of historical tax records.",
        featured: true,
    },
    {
        id: 45,
        category: "Tax Consultancy",
        title: "Tax Audit Preparation",
        description: "Preparation of records and documentation for tax audits.",
        featured: true,
    },
    {
        id: 46,
        category: "Data Analysis & Statistics",
        title: "Data Cleaning",
        description: "Cleaning, validating and preparing raw data for analysis.",
        featured: true,
    },
    {
        id: 47,
        category: "Data Analysis & Statistics",
        title: "Data Entry",
        description: "Accurate data entry into spreadsheets, databases and systems.",
        featured: false,
    },
    {
        id: 48,
        category: "Data Analysis & Statistics",
        title: "Data Analysis",
        description: "Professional analysis of quantitative and qualitative datasets.",
        featured: true,
    },
    {
        id: 49,
        category: "Data Analysis & Statistics",
        title: "Data Visualization",
        description: "Transform data into meaningful charts and visual reports.",
        featured: true,
    },
    {
        id: 50,
        category: "Data Analysis & Statistics",
        title: "Dashboard Development",
        description: "Interactive dashboards using Excel, Power BI and other BI tools.",
        featured: true,
    },
    {
        id: 51,
        category: "Data Analysis & Statistics",
        title: "Statistical Analysis",
        description: "Comprehensive statistical analysis for business and research.",
        featured: true,
    },
    {
        id: 52,
        category: "Data Analysis & Statistics",
        title: "Survey Data Analysis",
        description: "Analysis of survey responses and questionnaire results.",
        featured: true,
    },
    {
        id: 53,
        category: "Data Analysis & Statistics",
        title: "Questionnaire Analysis",
        description: "Coding and analysis of questionnaire data.",
        featured: false,
    },
    {
        id: 54,
        category: "Data Analysis & Statistics",
        title: "Regression Analysis",
        description: "Linear, multiple and logistic regression modelling.",
        featured: true,
    },
    {
        id: 55,
        category: "Data Analysis & Statistics",
        title: "Correlation Analysis",
        description: "Measure and interpret relationships between variables.",
        featured: false,
    },
    {
        id: 56,
        category: "Data Analysis & Statistics",
        title: "Time Series Analysis",
        description: "Analyze trends and seasonal patterns over time.",
        featured: true,
    },
    {
        id: 57,
        category: "Data Analysis & Statistics",
        title: "Forecasting",
        description: "Predict future outcomes using statistical forecasting models.",
        featured: true,
    },
    {
        id: 58,
        category: "Data Analysis & Statistics",
        title: "Business Intelligence Reports",
        description: "Generate actionable business intelligence reports.",
        featured: true,
    },
    {
        id: 59,
        category: "Data Analysis & Statistics",
        title: "KPI Development",
        description: "Design and measure Key Performance Indicators (KPIs).",
        featured: false,
    },
    {
        id: 60,
        category: "Data Analysis & Statistics",
        title: "Performance Analysis",
        description: "Analyze organizational and employee performance metrics.",
        featured: false,
    },
    {
        id: 61,
        category: "Data Analysis & Statistics",
        title: "Sales Analysis",
        description: "Evaluate sales performance, trends and opportunities.",
        featured: true,
    },
    {
        id: 62,
        category: "Data Analysis & Statistics",
        title: "Customer Analysis",
        description: "Analyze customer behaviour and business insights.",
        featured: false,
    },
    {
        id: 63,
        category: "Data Analysis & Statistics",
        title: "Financial Analysis",
        description: "Financial performance analysis and reporting.",
        featured: true,
    },
    {
        id: 64,
        category: "Data Analysis & Statistics",
        title: "Research Data Analysis",
        description: "Statistical analysis for academic and professional research.",
        featured: true,
    },
    {
        id: 65,
        category: "Data Analysis & Statistics",
        title: "SPSS Analysis",
        description: "Professional SPSS statistical analysis and interpretation.",
        featured: true,
    },
    {
        id: 66,
        category: "Data Analysis & Statistics",
        title: "Excel Analysis",
        description: "Advanced Excel analysis using formulas and PivotTables.",
        featured: true,
    },
    {
        id: 67,
        category: "Data Analysis & Statistics",
        title: "Power BI Dashboards",
        description: "Interactive Power BI dashboards and reports.",
        featured: true,
    },
    {
        id: 68,
        category: "Data Analysis & Statistics",
        title: "Python Data Analysis",
        description: "Data analysis using Python, Pandas and NumPy.",
        featured: true,
    },
    {
        id: 69,
        category: "Data Analysis & Statistics",
        title: "R Programming Analysis",
        description: "Statistical computing and visualization using R.",
        featured: false,
    },
    {
        id: 70,
        category: "Data Analysis & Statistics",
        title: "Report Writing",
        description: "Professional analytical and statistical report writing.",
        featured: true,
    },
    {
        id: 71,
        category: "Data Analysis & Statistics",
        title: "Interpretation of Results",
        description: "Clear explanation and interpretation of statistical findings.",
        featured: true,
    },
    {
        id: 72,
        category: "Data Analysis & Statistics",
        title: "Academic Data Analysis",
        description: "Data analysis for undergraduate and postgraduate projects.",
        featured: true,
    },
    {
        id: 73,
        category: "Data Analysis & Statistics",
        title: "Thesis Data Analysis",
        description: "Statistical analysis and reporting for thesis projects.",
        featured: true,
    },
    {
        id: 74,
        category: "Data Analysis & Statistics",
        title: "Dissertation Data Analysis",
        description: "Comprehensive dissertation data analysis services.",
        featured: true,
    },
    {
        id: 75,
        category: "Data Analysis & Statistics",
        title: "Business Analytics Consulting",
        description: "Strategic analytics solutions to support business decisions.",
        featured: true,
    },
    {
        id: 76,
        category: "Research & Academic Support",
        title: "Research Proposal Formatting",
        description: "Professional formatting of research proposals according to institutional guidelines.",
        featured: true,
    },
    {
        id: 77,
        category: "Research & Academic Support",
        title: "Research Methodology Guidance",
        description: "Expert guidance on selecting and applying appropriate research methodologies.",
        featured: true,
    },
    {
        id: 78,
        category: "Research & Academic Support",
        title: "Data Collection Templates",
        description: "Design and preparation of professional data collection tools.",
        featured: false,
    },
    {
        id: 79,
        category: "Research & Academic Support",
        title: "Questionnaire Design",
        description: "Design of structured and reliable research questionnaires.",
        featured: true,
    },
    {
        id: 80,
        category: "Research & Academic Support",
        title: "SPSS Analysis",
        description: "Statistical analysis of research data using SPSS.",
        featured: true,
    },
    {
        id: 81,
        category: "Research & Academic Support",
        title: "Statistical Interpretation",
        description: "Interpretation and explanation of statistical findings.",
        featured: true,
    },
    {
        id: 82,
        category: "Research & Academic Support",
        title: "Academic Editing",
        description: "Editing academic papers for grammar, clarity and consistency.",
        featured: false,
    },
    {
        id: 83,
        category: "Research & Academic Support",
        title: "Referencing",
        description: "Accurate referencing and citation management.",
        featured: false,
    },
    {
        id: 84,
        category: "Research & Academic Support",
        title: "APA Formatting",
        description: "Formatting documents according to APA style guidelines.",
        featured: false,
    },
    {
        id: 85,
        category: "Research & Academic Support",
        title: "MLA Formatting",
        description: "Formatting research work using MLA citation standards.",
        featured: false,
    },
    {
        id: 86,
        category: "Research & Academic Support",
        title: "Harvard Referencing",
        description: "Professional Harvard referencing and citation services.",
        featured: false,
    },
    {
        id: 87,
        category: "Research & Academic Support",
        title: "IEEE Referencing",
        description: "Formatting engineering and technical documents using IEEE style.",
        featured: false,
    },
    {
        id: 88,
        category: "Research & Academic Support",
        title: "Plagiarism Checking",
        description: "Similarity checking and plagiarism reduction guidance.",
        featured: true,
    },
    {
        id: 89,
        category: "Research & Academic Support",
        title: "Thesis Formatting",
        description: "Professional thesis formatting according to university requirements.",
        featured: true,
    },
    {
        id: 90,
        category: "Research & Academic Support",
        title: "Dissertation Formatting",
        description: "Complete dissertation formatting and document preparation.",
        featured: true,
    },
    {
        id: 91,
        category: "Web Design & Development",
        title: "Business Websites",
        description: "Professional websites for small and medium-sized businesses.",
        featured: true,
    },
    {
        id: 92,
        category: "Web Design & Development",
        title: "Company Websites",
        description: "Corporate websites with modern responsive designs.",
        featured: true,
    },
    {
        id: 93,
        category: "Web Design & Development",
        title: "School Websites",
        description: "Modern websites for schools, colleges and universities.",
        featured: false,
    },
    {
        id: 94,
        category: "Web Design & Development",
        title: "Church Websites",
        description: "Professional church websites with event and media support.",
        featured: false,
    },
    {
        id: 95,
        category: "Web Design & Development",
        title: "NGO Websites",
        description: "Responsive websites for NGOs and nonprofit organizations.",
        featured: false,
    },
    {
        id: 96,
        category: "Web Design & Development",
        title: "E-Commerce Websites",
        description: "Online stores with secure payment integration.",
        featured: true,
    },
    {
        id: 97,
        category: "Web Design & Development",
        title: "Online Booking Systems",
        description: "Appointment and reservation systems for businesses.",
        featured: true,
    },
    {
        id: 98,
        category: "Web Design & Development",
        title: "Portfolio Websites",
        description: "Personal and professional portfolio websites.",
        featured: false,
    },
    {
        id: 99,
        category: "Web Design & Development",
        title: "Landing Pages",
        description: "High-converting landing pages for marketing campaigns.",
        featured: true,
    },
    {
        id: 100,
        category: "Web Design & Development",
        title: "Responsive Web Design",
        description: "Mobile-friendly websites optimized for all devices.",
        featured: true,
    },
    {
        id: 101,
        category: "Web Design & Development",
        title: "Website Redesign",
        description: "Modern redesigns for outdated websites.",
        featured: false,
    },
    {
        id: 102,
        category: "Web Design & Development",
        title: "Website Maintenance",
        description: "Ongoing website updates, security and maintenance.",
        featured: true,
    },
    {
        id: 103,
        category: "Web Design & Development",
        title: "Domain Registration Assistance",
        description: "Help registering and managing website domains.",
        featured: false,
    },
    {
        id: 104,
        category: "Web Design & Development",
        title: "Web Hosting Assistance",
        description: "Professional hosting setup and migration services.",
        featured: false,
    },
    {
        id: 105,
        category: "Web Design & Development",
        title: "Website Security",
        description: "Website security audits and protection services.",
        featured: true,
    },
    {
        id: 106,
        category: "Web Design & Development",
        title: "Search Engine Optimization (SEO)",
        description: "Improve website visibility and search rankings.",
        featured: true,
    },
    {
        id: 107,
        category: "Web Design & Development",
        title: "Speed Optimization",
        description: "Improve website performance and loading speed.",
        featured: true,
    },
    {
        id: 108,
        category: "Web Design & Development",
        title: "CMS Development",
        description: "Custom content management system development.",
        featured: false,
    },
    {
        id: 109,
        category: "Web Design & Development",
        title: "WordPress Development",
        description: "Professional WordPress websites and customization.",
        featured: true,
    },
    {
        id: 110,
        category: "Web Design & Development",
        title: "Laravel Development",
        description: "Modern Laravel web application development.",
        featured: true,
    },
    {
        id: 111,
        category: "Web Design & Development",
        title: "Django Development",
        description: "Scalable Django web application development.",
        featured: true,
    },
    {
        id: 112,
        category: "Web Design & Development",
        title: "React Applications",
        description: "Interactive React and Next.js web applications.",
        featured: true,
    },
    {
        id: 113,
        category: "Software Development",
        title: "Desktop Applications",
        description: "Custom desktop software for Windows and cross-platform environments.",
        featured: true,
    },
    {
        id: 114,
        category: "Software Development",
        title: "Custom Business Systems",
        description: "Tailor-made business management systems.",
        featured: true,
    },
    {
        id: 115,
        category: "Software Development",
        title: "Inventory Systems",
        description: "Inventory and stock management solutions.",
        featured: true,
    },
    {
        id: 116,
        category: "Software Development",
        title: "Payroll Systems",
        description: "Employee payroll processing systems.",
        featured: true,
    },
    {
        id: 117,
        category: "Software Development",
        title: "POS Systems",
        description: "Point of Sale systems for retail businesses.",
        featured: true,
    },
    {
        id: 118,
        category: "Software Development",
        title: "School Management Systems",
        description: "Digital systems for managing educational institutions.",
        featured: false,
    },
    {
        id: 119,
        category: "Software Development",
        title: "Hospital Systems",
        description: "Healthcare and hospital information systems.",
        featured: false,
    },
    {
        id: 120,
        category: "Software Development",
        title: "Sacco Systems",
        description: "Savings and Credit Cooperative management software.",
        featured: false,
    },
    {
        id: 121,
        category: "Software Development",
        title: "CRM Development",
        description: "Customer Relationship Management systems.",
        featured: true,
    },
    {
        id: 122,
        category: "Software Development",
        title: "ERP Solutions",
        description: "Enterprise Resource Planning software.",
        featured: true,
    },
    {
        id: 123,
        category: "Software Development",
        title: "API Integration",
        description: "Integration of third-party APIs into applications.",
        featured: true,
    },
    {
        id: 124,
        category: "Software Development",
        title: "Database Design",
        description: "Relational and NoSQL database architecture.",
        featured: true,
    },
    {
        id: 125,
        category: "Software Development",
        title: "Database Management",
        description: "Database administration and optimization.",
        featured: false,
    },
    {
        id: 126,
        category: "Software Development",
        title: "Software Maintenance",
        description: "Continuous software updates and maintenance.",
        featured: false,
    },
    {
        id: 127,
        category: "Software Development",
        title: "Software Testing",
        description: "Functional, performance and quality assurance testing.",
        featured: false,
    },
    {
        id: 128,
        category: "Artificial Intelligence",
        title: "AI Consultation",
        description: "Professional AI strategy and consultation services.",
        featured: true,
    },
    {
        id: 129,
        category: "Artificial Intelligence",
        title: "AI Training",
        description: "Hands-on Artificial Intelligence training programs.",
        featured: true,
    },
    {
        id: 130,
        category: "Artificial Intelligence",
        title: "AI Literacy Training",
        description: "Understanding AI tools and technologies.",
        featured: false,
    },
    {
        id: 131,
        category: "Artificial Intelligence",
        title: "AI Productivity Training",
        description: "Using AI tools to improve workplace productivity.",
        featured: true,
    },
    {
        id: 132,
        category: "Artificial Intelligence",
        title: "ChatGPT Training",
        description: "Practical ChatGPT training for professionals.",
        featured: true,
    },
    {
        id: 133,
        category: "Artificial Intelligence",
        title: "Prompt Engineering",
        description: "Designing effective prompts for AI systems.",
        featured: true,
    },
    {
        id: 134,
        category: "Artificial Intelligence",
        title: "AI for Business",
        description: "AI implementation strategies for businesses.",
        featured: true,
    },
    {
        id: 135,
        category: "Artificial Intelligence",
        title: "AI Content Assistance",
        description: "Content creation powered by Artificial Intelligence.",
        featured: false,
    },
    {
        id: 136,
        category: "Artificial Intelligence",
        title: "AI Automation",
        description: "Automating business processes using AI.",
        featured: true,
    },
    {
        id: 137,
        category: "Artificial Intelligence",
        title: "AI Research Assistance",
        description: "AI-powered research and information synthesis.",
        featured: false,
    },
    {
        id: 138,
        category: "Artificial Intelligence",
        title: "AI Workflow Integration",
        description: "Integrating AI into everyday business workflows.",
        featured: true,
    },
    {
        id: 139,
        category: "ICT Consultancy",
        title: "ICT Consultancy",
        description: "Professional ICT advisory services for businesses and organizations.",
        featured: true,
    },
    {
        id: 140,
        category: "ICT Consultancy",
        title: "Digital Transformation",
        description: "Helping organizations adopt modern digital technologies.",
        featured: true,
    },
    {
        id: 141,
        category: "ICT Consultancy",
        title: "Technology Advisory",
        description: "Strategic technology planning and implementation guidance.",
        featured: true,
    },
    {
        id: 142,
        category: "ICT Consultancy",
        title: "Business Process Automation",
        description: "Automating repetitive business operations using technology.",
        featured: true,
    },
    {
        id: 143,
        category: "ICT Consultancy",
        title: "ICT Project Planning",
        description: "Planning and management of ICT implementation projects.",
        featured: false,
    },
    {
        id: 144,
        category: "ICT Consultancy",
        title: "System Documentation",
        description: "Preparation of technical and user documentation.",
        featured: false,
    },
    {
        id: 145,
        category: "ICT Consultancy",
        title: "Network Consultation",
        description: "Network planning, setup and optimization services.",
        featured: false,
    },
    {
        id: 146,
        category: "ICT Consultancy",
        title: "Computer Setup",
        description: "Installation and configuration of computer systems.",
        featured: false,
    },
    {
        id: 147,
        category: "ICT Consultancy",
        title: "Office ICT Solutions",
        description: "Complete ICT solutions for modern office environments.",
        featured: true,
    },
    {
        id: 148,
        category: "Graphic Design",
        title: "Logo Design",
        description: "Professional logo creation and brand identity development.",
        featured: true,
    },
    {
        id: 149,
        category: "Graphic Design",
        title: "Poster Design",
        description: "Creative posters for businesses and events.",
        featured: false,
    },
    {
        id: 150,
        category: "Graphic Design",
        title: "Flyer Design",
        description: "Professional marketing flyers and promotional materials.",
        featured: false,
    },
    {
        id: 151,
        category: "Graphic Design",
        title: "Brochure Design",
        description: "Company brochures and marketing booklets.",
        featured: true,
    },
    {
        id: 152,
        category: "Graphic Design",
        title: "Business Card Design",
        description: "Modern business card designs for professionals.",
        featured: false,
    },
    {
        id: 153,
        category: "Graphic Design",
        title: "Company Profile Design",
        description: "Professional company profile creation.",
        featured: true,
    },
    {
        id: 154,
        category: "Graphic Design",
        title: "Banner Design",
        description: "Indoor and outdoor advertising banners.",
        featured: false,
    },
    {
        id: 155,
        category: "Graphic Design",
        title: "Roll-up Banner Design",
        description: "Corporate exhibition and promotional roll-up banners.",
        featured: false,
    },
    {
        id: 156,
        category: "Graphic Design",
        title: "Certificate Design",
        description: "Certificates for institutions, events and organizations.",
        featured: false,
    },
    {
        id: 157,
        category: "Graphic Design",
        title: "Invitation Card Design",
        description: "Professional invitation cards for all occasions.",
        featured: false,
    },
    {
        id: 158,
        category: "Graphic Design",
        title: "Social Media Poster Design",
        description: "Creative graphics for Facebook, Instagram and LinkedIn.",
        featured: true,
    },
    {
        id: 159,
        category: "Graphic Design",
        title: "CV Design",
        description: "Professionally designed CV layouts.",
        featured: true,
    },
    {
        id: 160,
        category: "Graphic Design",
        title: "Portfolio Design",
        description: "Professional portfolio creation for individuals and businesses.",
        featured: false,
    },
    {
        id: 161,
        category: "Graphic Design",
        title: "Brand Identity Design",
        description: "Complete branding packages for businesses.",
        featured: true,
    },
    {
        id: 162,
        category: "Computer & Internet Services",
        title: "Internet Browsing",
        description: "Fast and reliable internet browsing services.",
        featured: false,
    },
    {
        id: 163,
        category: "Computer & Internet Services",
        title: "Email Creation",
        description: "Professional email account creation and setup.",
        featured: false,
    },
    {
        id: 164,
        category: "Computer & Internet Services",
        title: "Email Setup",
        description: "Configuration of email accounts on devices.",
        featured: false,
    },
    {
        id: 165,
        category: "Computer & Internet Services",
        title: "Online Applications",
        description: "Assistance with various online applications.",
        featured: true,
    },
    {
        id: 166,
        category: "Computer & Internet Services",
        title: "File Conversion",
        description: "Conversion between PDF, Word, Excel and other formats.",
        featured: false,
    },
    {
        id: 167,
        category: "Computer & Internet Services",
        title: "PDF Editing",
        description: "Editing and modification of PDF documents.",
        featured: false,
    },
    {
        id: 168,
        category: "Computer & Internet Services",
        title: "Document Scanning",
        description: "High-quality document scanning services.",
        featured: false,
    },
    {
        id: 169,
        category: "Computer & Internet Services",
        title: "OCR Services",
        description: "Optical Character Recognition for scanned documents.",
        featured: false,
    },
    {
        id: 170,
        category: "Computer & Internet Services",
        title: "Document Digitization",
        description: "Conversion of physical documents into digital formats.",
        featured: true,
    },
    {
        id: 171,
        category: "Computer & Internet Services",
        title: "Cloud Storage Assistance",
        description: "Setup and management of secure cloud storage solutions.",
        featured: false,
    },
];
